#!/usr/bin/env python3
"""ACE local-storage bootstrap — scaffolds the three stores of spec/11 for a NEW deployment.

  control plane  ACE_STORE  (git; a remote is optional and must be PRIVATE)
  content plane  ACE_LOCAL  (git; NEVER a remote — personal/IP content stays on this machine)
  hub vault      ACE_HUB    (git; local; open it as an Obsidian vault)

Safe by construction: prints the plan unless --apply; never deletes; never overwrites an existing file;
only `git init`s a store that has no .git yet, and only commits the scaffold files it created itself
(never `git add -A` in a folder that may already hold someone's files). It creates empty stores —
it never copies state or content from another ACE deployment.

Usage:  python deploy/bootstrap_stores.py [--apply] [--store PATH] [--local PATH] [--hub PATH]
Paths default to ACE_STORE / ACE_LOCAL / ACE_HUB (the same variables the engine reads), then to the
reference deployment's paths.
"""
import argparse, os, subprocess, sys

REF = {"store": r"F:\git\ACE_storage", "local": r"F:\ACE_local", "hub": r"F:\ACE_hub"}
ENV = {"store": "ACE_STORE", "local": "ACE_LOCAL", "hub": "ACE_HUB"}
BOT = ["-c", "user.name=ACE Loop", "-c", "user.email=loop@ace.local"]  # PA-2: machine writes are attributable

# One-line purpose per directory, from spec/11 (layouts + binding writer matrix).
LAYOUT = {
    "store": {
        "": "ACE control plane — state, metadata, hashes. No PHI, no content excerpts, no credentials. Remote optional and PRIVATE only.",
        "inbox": "capture metadata stubs (hash + timestamp; content stays in ACE_LOCAL). Panels append stubs only.",
        "packets": "session packets and resume packets GENERATED by the engine; panels read only.",
        "outbox": "the sole path panels write exit packages (X-<id>/EXIT_PACKAGE.json), awaiting `ace_engine.py validate`.",
        "pending": "validated packages awaiting the owner's review (hub_pending). Engine writes; owner reviews.",
        "state": "machine-readable truth the loops consume (projects.json). Engine single-writer.",
        "audit": "append-only events.jsonl — every transition, write-ahead for accepts. Engine single-writer.",
        "receipts": "acknowledgments: transfer, closure, approval receipts.",
        "seals": "frozen references + _sha256 manifests (Red-Queen epoch contracts).",
        "quality": "FMEA log, edge cases, evals — system-level, no personal or clinical content.",
        "quality/edge_cases": "edge-case reports (pointer + sha256, synthetic reproductions only).",
        "quality/evals": "evaluation records.",
        "local_manifests": "metadata-only mirror of ACE_LOCAL/manifests (manifest loop single-writer).",
        "bridge/exports": "ACE-P -> ACE-C stubs, receipts and hashes only (package bodies never on this plane).",
        "bridge/imports": "ACE-C -> ACE-P stubs + acknowledgments (no PHI, ever).",
        "archive/applied": "accepted packages, moved here by the engine — never deleted.",
        "archive/rejected": "rejected packages, moved here by the engine — never deleted.",
    },
    "local": {
        "": "ACE content plane — personal/IP content. Local git, NEVER a remote. Backed up only to local/offline media.",
        "inbox": "universal capture (free text + optional @date); the clarify loop reads it.",
        "research": "research / proposals / prototyping — owner, or a panel inside its declared write boundary.",
        "artifacts": "shipped evidence artifacts, one folder per unit (engine writes on accepted evidence).",
        "manifests": "GENERATED sha256 index of this plane (manifest loop single-writer).",
        "archive": "superseded content — moved here, never deleted.",
    },
    "hub": {
        "": "ACE hub vault — open in Obsidian. Owner writes freely except views/. Local git; no remote needed.",
        "inbox": "human capture surface (Ctrl+N lands here); the clarify loop reads it.",
        "projects": "one note per project, written by the engine on accept.",
        "commitments": "commitments and returns.",
        "evidence": "evidence and handoff records.",
        "views": "GENERATED views (Today, Pending Panel Updates, Commitments and Return, Weekly Review) — hand edits are lost.",
    },
}
GITIGNORE = {"store": ".ace_tmp_*\n*.tmp\n", "local": ".ace_tmp_*\n*.tmp\n", "hub": ".ace_tmp_*\n*.tmp\n.obsidian/workspace*\n"}
ENGINE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "engine", "ace_engine.py")

# Hub initialization beyond folders (mirrors the reference hub): Ctrl+N lands in inbox/, a root note with the
# surfaces and the capture/gesture marks (spec/13; clarify_loop.py, gesture_watcher.py), and engine-generated views.
OBSIDIAN_APP = '{"newFileLocation": "folder", "newFileFolderPath": "inbox"}\n'
HUB_README = """# ACE hub vault

Open this folder in Obsidian ("Open folder as vault"). It is a **local** vault — never inside the control-plane
repo; git here is local versioning only (no remote). Cross-device use, if wanted: Obsidian Sync on the owner's
own account, enabled by the owner in-app.

## Surfaces (six maximum)

| folder / view | purpose |
|---|---|
| `inbox/` | CAPTURE HERE — Ctrl+N lands in this folder; free text, one note per thought |
| `views/Today.md` | narrow execution view (generated) |
| `views/Pending Panel Updates.md` | proposed changes awaiting review (generated from the control plane's `pending/`) |
| `views/Commitments and Return.md` | next actions, agenda / waiting-for by person, scheduled returns (generated) |
| `views/Weekly Review.md` | reliability + conversion scoreboards (generated) |
| `projects/` · `commitments/` · `evidence/` | control-level records written on accepted transitions |

## Marks

- **Capture** (a note in `inbox/`): `@YYYY-MM-DD` return date · `@name` person (agenda / waiting-for) ·
  `@call` `@read` `@desk` `@msg` category · hedge words ("maybe", "not sure", "thinking out loud", a trailing `..`)
  route the note to the idea queue instead of making a commitment. The clarify loop reads only these marks — it never guesses.
- **Review** (in `views/Pending Panel Updates.md`): tick `- [x]` = accept · `~~strike~~` = reject ·
  `@YYYY-MM-DD` suffix = defer until that date. Then run `python <repo>/engine/gesture_watcher.py`
  (or let the scheduled tick do it, once the owner activates it).

## Rules

- `views/` is regenerated by the engine — hand edits are lost, except ticks / strikes / defers in the Pending
  view, which the gesture watcher harvests first. Regenerate with `python <repo>/engine/ace_engine.py views`.
- Notes here are control-level records (title, state, dates, pointers); content bodies live in the content
  plane; personal-sensitive items use alias titles; clinical items appear only as short aliases.
- The engine writes only on accepted transitions; the owner writes freely; nothing is deleted.
"""

def norm(p): return os.path.normcase(os.path.abspath(p))

def paths(args):
    return {k: getattr(args, k) or os.environ.get(ENV[k]) or REF[k] for k in REF}

def plan(roots):
    """Every (kind, path, content) the scaffold needs that does not exist yet."""
    todo = []
    for k, root in roots.items():
        for rel, purpose in LAYOUT[k].items():
            d = os.path.join(root, *rel.split("/")) if rel else root
            if not os.path.isdir(d): todo.append(("dir", d, None))
            readme = os.path.join(d, "README.md")
            if not os.path.exists(readme):
                title = rel or os.path.basename(root.rstrip("\\/"))
                todo.append(("file", readme, HUB_README if (k, rel) == ("hub", "") else f"# {title}\n\n{purpose}\n"))
        gi = os.path.join(root, ".gitignore")
        if not os.path.exists(gi): todo.append(("file", gi, GITIGNORE[k]))
        if k == "hub":
            app = os.path.join(root, ".obsidian", "app.json")
            if not os.path.exists(app): todo.append(("file", app, OBSIDIAN_APP))
            if not os.path.exists(os.path.join(root, "views", "Today.md")):
                todo.append(("views", os.path.join(root, "views"), roots))
        if not os.path.isdir(os.path.join(root, ".git")): todo.append(("git", root, k))
    return todo

def apply(todo):
    created = {}
    for kind, p, content in todo:
        if kind == "dir":
            os.makedirs(p, exist_ok=True)
        elif kind == "file":
            os.makedirs(os.path.dirname(p), exist_ok=True)
            with open(p, "x", encoding="utf-8", newline="\n") as f:  # "x": refuse to overwrite
                f.write(content)
            created.setdefault(p, True)
    for kind, views, roots in todo:  # the engine is the views' single writer (spec/11) — let it generate them
        if kind != "views": continue
        before = set(os.listdir(views))
        env = {**os.environ, "ACE_STORE": roots["store"], "ACE_LOCAL": roots["local"], "ACE_HUB": roots["hub"]}
        subprocess.run([sys.executable, ENGINE, "views"], env=env, check=True, capture_output=True)
        for f in set(os.listdir(views)) - before: created.setdefault(os.path.join(views, f), True)
    for kind, root, k in todo:
        if kind != "git": continue
        subprocess.run(["git", "init", "-q", "-b", "main", root], check=True)
        base = norm(root) + os.sep
        mine = [os.path.relpath(p, root) for p in created if norm(p).startswith(base)]
        if mine:
            subprocess.run(["git", "-C", root, "add", "--"] + mine, check=True)
            subprocess.run(["git", "-C", root] + BOT + ["commit", "-q", "-m", f"deploy: scaffold ACE {k} store (bootstrap_stores.py)"], check=True)

def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--apply", action="store_true", help="create what is missing (default: print the plan only)")
    for k in REF: ap.add_argument(f"--{k}", help=f"path of the {k} store (default: ${ENV[k]}, then {REF[k]})")
    args = ap.parse_args()
    roots = paths(args)
    ns = [norm(p) for p in roots.values()]
    if len(set(ns)) < 3 or any(a != b and a.startswith(b + os.sep) for a in ns for b in ns):
        print("REFUSED: the three stores must be three separate folders, none inside another"); return 2
    todo = plan(roots)
    for k, p in roots.items(): print(f"{k:5} -> {p}")
    if not todo:
        print("nothing to do — all three stores are already scaffolded"); return 0
    for kind, p, _ in todo: print(f"  {'would ' if not args.apply else ''}{kind:4} {p}")
    if not args.apply:
        print("\nplan only — re-run with --apply to create the items above (nothing existing is changed)"); return 0
    apply(todo)
    print(f"\ncreated {len(todo)} item(s). Next: python deploy/verify_deploy.py")
    return 0

if __name__ == "__main__":
    sys.exit(main())
